const List<Map<String, String>> countries = [
  {'name': 'Andorra', 'code': 'ad'},
  {'name': 'Angola', 'code': 'ao'},
  {'name': 'Argentina', 'code': 'ar'},
  {'name': 'Armenia', 'code': 'am'},
  {'name': 'Australia', 'code': 'au'},
  {'name': 'Austria', 'code': 'at'},
  {'name': 'Azerbaijan', 'code': 'az'},
  {'name': 'Bahamas (the)', 'code': 'bs'},
  {'name': 'Bahrain', 'code': 'bh'},
  {'name': 'Bangladesh', 'code': 'bd'},
  {'name': 'Belarus', 'code': 'by'},
  {'name': 'Belgium', 'code': 'be'},
  {'name': 'Bhutan', 'code': 'bt'},
  {'name': 'Bolivia', 'code': 'bo'},
  {'name': 'Bolivia (Plurinational State of)', 'code': 'bo'},
  {'name': 'Bosnia and Herzegovina', 'code': 'ba'},
  {'name': 'Botswana', 'code': 'bw'},
  {'name': 'Brazil', 'code': 'br'},
  {'name': 'Brunei Darussalam', 'code': 'bn'},
  {'name': 'Brunei Darussalam', 'code': 'bg'},
  {'name': 'Burkina Faso', 'code': 'bf'},
  {'name': 'Burundi', 'code': 'bi'},
  {'name': 'Cabo Verde', 'code': 'cv'},
  {'name': 'Cameroon', 'code': 'cm'},
  {'name': 'Canada', 'code': 'ca'},
  {'name': 'Central African Republic (the)', 'code': 'cf'},
  {'name': 'Chad', 'code': 'td'},
  {'name': 'Chile', 'code': 'cl'},
  {'name': 'China', 'code': 'cn'},
  {'name': 'Colombia', 'code': 'co'},
  {'name': 'Congo (the Democratic Republic of the)', 'code': 'cd'},
  {'name': 'Congo (the)', 'code': 'cg'},
  {'name': 'Costa Rica', 'code': 'cr'},
  {'name': 'Croatia', 'code': 'hr'},
  {'name': 'Cuba', 'code': 'cu'},
  {'name': 'Cyprus', 'code': 'cy'},
  {'name': 'Czechia', 'code': 'cz'},
  {'name': 'Côte d\'Ivoire', 'code': 'ci'},
  {'name': 'Côte d\'Ivoire', 'code': 'dk'},
  {'name': 'Djibouti', 'code': 'dj'},
  {'name': 'Dominican Republic (the)', 'code': 'do'},
  {'name': 'Ecuador', 'code': 'ec'},
  {'name': 'Egypt', 'code': 'eg'},
  {'name': 'El Salvador', 'code': 'sv'},
  {'name': 'Estonia', 'code': 'ee'},
  {'name': 'Ethiopia', 'code': 'et'},
  {'name': 'Faroe Islands (the)', 'code': 'fo'},
  {'name': 'Finland', 'code': 'fi'},
  {'name': 'France', 'code': 'fr'},
  {'name': 'Georgia', 'code': 'ge'},
  {'name': 'Germany', 'code': 'de'},
  {'name': 'Greece', 'code': 'gr'},
  {'name': 'Guatemala', 'code': 'gt'},
  {'name': 'Guinea', 'code': 'gn'},
  {'name': 'Haiti', 'code': 'ht'},
  {'name': 'Honduras', 'code': 'hn'},
  {'name': 'Hong Kong', 'code': 'hk'},
  {'name': 'Hungary', 'code': 'hu'},
  {'name': 'India', 'code': 'in'},
  {'name': 'Indonesia', 'code': 'id'},
  {'name': 'Iran (Islamic Republic of)', 'code': 'ir'},
  {'name': 'Iraq', 'code': 'iq'},
  {'name': 'Ireland', 'code': 'ie'},
  {'name': 'Israel', 'code': 'il'},
  {'name': 'Italy', 'code': 'it'},
  {'name': 'Jamaica', 'code': 'jm'},
  {'name': 'Japan', 'code': 'jp'},
  {'name': 'Kazakhstan', 'code': 'kz'},
  {'name': 'Kenya', 'code': 'ke'},
  {'name': 'Korea (the Republic of)', 'code': 'kr'},
  {'name': 'Kosovo', 'code': 'xk'},
  {'name': 'Kyrgyzstan', 'code': 'kg'},
  {'name': 'Lao People\'s Democratic Republic (the)', 'code': 'la'},
  {'name': 'Latvia', 'code': 'lv'},
  {'name': 'Liechtenstein', 'code': 'li'},
  {'name': 'Lithuania', 'code': 'lt'},
  {'name': 'Luxembourg', 'code': 'lu'},
  {'name': 'Malaysia', 'code': 'my'},
  {'name': 'Mali', 'code': 'ml'},
  {'name': 'Malta', 'code': 'mt'},
  {'name': 'Mexico', 'code': 'mx'},
  {'name': 'Moldova (the Republic of)', 'code': 'md'},
  {'name': 'Montenegro', 'code': 'me'},
  {'name': 'Morocco', 'code': 'ma'},
  {'name': 'Mozambique', 'code': 'mz'},
  {'name': 'Myanmar', 'code': 'mm'},
  {'name': 'Namibia', 'code': 'na'},
  {'name': 'Nepal', 'code': 'np'},
  {'name': 'Netherlands (the)', 'code': 'nl'},
  {'name': 'New Zealand', 'code': 'nz'},
  {'name': 'Nicaragua', 'code': 'ni'},
  {'name': 'Nigeria', 'code': 'ng'},
  {'name': 'Norway', 'code': 'no'},
  {'name': 'Oman', 'code': 'om'},
  {'name': 'Pakistan', 'code': 'pk'},
  {'name': 'Palestine, State of', 'code': 'ps'},
  {'name': 'Panama', 'code': 'pa'},
  {'name': 'Paraguay', 'code': 'oy'},
  {'name': 'Peru', 'code': 'pe'},
  {'name': 'Philippines (the)', 'code': 'ph'},
  {'name': 'Poland', 'code': 'pl'},
  {'name': 'Portugal', 'code': 'pt'},
  {'name': 'Puerto Rico', 'code': 'pr'},
  {'name': 'Qatar', 'code': 'qa'},
  {'name': 'Republic of North Macedonia', 'code': 'mk'},
  {'name': 'Romania', 'code': 'ro'},
  {'name': 'Russian Federation (the)', 'code': 'ru'},
  {'name': 'Rwanda', 'code': 'rw'},
  {'name': 'San Marino', 'code': 'sm'},
  {'name': 'Saudi Arabia', 'code': 'sa'},
  {'name': 'Serbia', 'code': 'rs'},
  {'name': 'Sierra Leone', 'code': 'sl'},
  {'name': 'Slovakia', 'code': 'sk'},
  {'name': 'Slovenia', 'code': 'si'},
  {'name': 'South Africa', 'code': 'za'},
  {'name': 'Spain', 'code': 'es'},
  {'name': 'Sri Lanka', 'code': 'lk'},
  {'name': 'Sudan (the)', 'code': 'sd'},
  {'name': 'Sweden', 'code': 'se'},
  {'name': 'Switzerland', 'code': 'ch'},
  {'name': 'Syrian Arab Republic', 'code': 'sy'},
  {'name': 'Taiwan (Province of China)', 'code': 'tw'},
  {'name': 'Tajikistan', 'code': 'tj'},
  {'name': 'Thailand', 'code': 'th'},
  {'name': 'Turkey', 'code': 'tr'},
  {'name': 'Uganda', 'code': 'ug'},
  {'name': 'Ukraine', 'code': 'ua'},
  {'name': 'United Arab Emirates (the)', 'code': 'ae'},
  {
    'name': 'United Kingdom of Great Britain and Northern Ireland (the)',
    'code': 'gb'
  },
  {'name': 'United States of America (the)', 'code': 'us'},
  {'name': 'Uruguay', 'code': 'uy'},
  {'name': 'Uzbekistan', 'code': 'uz'},
  {'name': 'Venezuela (Bolivarian Republic of)', 'code': 've'},
  {'name': 'Viet Nam', 'code': 'vn'},
  {'name': 'Yemen', 'code': 'ye'},
  {'name': 'Zambia', 'code': 'zm'},
  {'name': 'Zimbabwe', 'code': 'zw'},
];
